Add some initial documentation for query caches
neo4j/docs-cypher pull request #521
Opened 2023-04-20 13:29 UTC by hedengran

2023-04-20 13:31 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-cypher-521.surge.sh
<!-- Sticky Pull Request Comment -->

2023-04-21 08:28 UTC, hedengran commented
Questions to reviewers: Is this the correct location for the pages? I feel like putting it at the same level as "Syntax", "Clauses", "Administration", etc. might be shedding a bit too much light on a pretty advanced topic. Maybe it should even end up in the Operations Manual instead?

2023-04-21 11:54 UTC, sherfert requested changes
I think the location of the pages is good.

However, it seems the options are not described in the operations manual (https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/) - at least not in the currently published version.

Is that already changed in `dev` of the operations manual? If not, I think this should go hand in hand. And then, from here, you can insert links to the relevant part of the website linked above.

2023-04-21 11:54 UTC, sherfert commented on modules/ROOT/pages/query-caches/index.adoc
> +The max number of entries per cache is configured with `server.memory.query_cache.per_db_cache_num_entries`.
```suggestion
The maximum number of entries per cache is configured with `server.memory.query_cache.per_db_cache_num_entries`.
```

2023-04-21 11:54 UTC, sherfert commented on modules/ROOT/pages/query-caches/unified-query-caches.adoc
> +When this feature is enabled, all databases will utilize only on set of query caches.
```suggestion
When this feature is enabled, all databases will utilize only one set of query caches.
```

2023-04-21 12:03 UTC, hedengran commented
> However, it seems the options are not described in the operations manual

Yes, currently they are not. That's what I meant during standup this morning, that I just learned that they're not automatically added to where you linked. But @renetapopova is on it and will added soon I think. 

>  I think this should go hand in hand. And then, from here, you can insert links to the relevant part of the website linked above.

Yes that's a very good idea.

2023-04-24 08:00 UTC, sherfert commented on modules/ROOT/pages/query-caches/index.adoc
> +For more information, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/[Operations Manual -> Configuration settings].
Has the operations manual been updated then?

2023-04-24 08:00 UTC, sherfert commented on modules/ROOT/pages/query-caches/index.adoc
> +| server.memory.query_cache.sharing_enabled
I would still find it useful if all these mentions of the exact settings were clickable links to the exact sub-section in the operations manual.

2023-04-24 08:07 UTC, hedengran commented on modules/ROOT/pages/query-caches/index.adoc
> +For more information, see link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/configuration-settings/[Operations Manual -> Configuration settings].
Yes: https://neo4j.com/docs/operations-manual/5/reference/configuration-settings/#config_server.memory.query_cache.sharing_enabled

2023-04-24 10:17 UTC, renetapopova approved these changes

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/unified-query-caches.adoc
> +While databases utilize the same set of caches, a database may not observe entries originating from other databases.
```suggestion
While databases use the same set of caches, a database may not observe entries originating from other databases.
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/unified-query-caches.adoc
> +When this option is turned on, the cache space available to all databases is configured with
```suggestion
When this option is turned on, the cache space available to all databases is configured with `server.memory.query_cache.shared_cache_num_entries`.
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/unified-query-caches.adoc
> +`server.memory.query_cache.shared_cache_num_entries`.
```suggestion
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/index.adoc
> +To combat this, and improve predictability on memory consumption,
```suggestion
To combat this and improve the predictability of memory consumption, it is possible to configure the DBMS to use only one set of caches for all databases.
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/index.adoc
> +it is possible to configure the DBMS such that only one set of caches is utilized for all databases.
```suggestion
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/index.adoc
> +More information on this topic can be found in the following section:
```suggestion
For more information, see xref:query-caches/unified-query-caches.adoc[]
```

2023-04-24 10:17 UTC, renetapopova commented on modules/ROOT/pages/query-caches/index.adoc
> +* xref:query-caches/unified-query-caches.adoc[]
```suggestion
```

2023-04-24 14:26 UTC, sherfert approved these changes
:sparkle:

2023-04-24 14:47 UTC, merged