Deprecate self-references in CREATE clauses
neo4j/docs-cypher pull request #607
Opened 2023-06-13 09:26 UTC by hedengran

2023-06-14 09:28 UTC, sherfert commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +[[cypher-deprecations-additions-removals-5.8]]
```suggestion
[[cypher-deprecations-additions-removals-5.9]]
```

2023-06-14 09:46 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-cypher-607.surge.sh
<!-- Sticky Pull Request Comment -->

2023-06-20 13:05 UTC, sherfert reviewed
Sorry, I had this pending for a while but forgot to submit the review.

2023-06-20 13:05 UTC, sherfert commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +and then referencing a property of that entity in the same create clause is deprecated.
```suggestion
and then referencing that entity in the same create clause is deprecated.
```

This is not really about the property part, right? Any other reference, e.g. `labels(a)` would also be deprecated?

2023-06-20 14:44 UTC, hedengran commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +and then referencing a property of that entity in the same create clause is deprecated.
You're right, "referencing a property" does not catch it all, forgot about those other cases. But some references are still valid, e.g. `CREATE (a)-[:REL]->(a)`. Not sure how to capture that in one sentence.

2023-06-21 08:53 UTC, sherfert commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +and then referencing a property of that entity in the same create clause is deprecated.
Does "referencing that entity in a property definition in the same create clause ..." catch all the cases?

2023-06-22 06:31 UTC, hedengran commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +and then referencing a property of that entity in the same create clause is deprecated.
Yeah I think that works, thanks!

2023-06-22 07:25 UTC, sherfert approved these changes

2023-06-22 09:32 UTC, JPryce-Aklundh requested changes
looks good overall 👍 - I made two suggestions:

2023-06-22 09:32 UTC, JPryce-Aklundh commented on modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
> +Please split your `CREATE` into two separate clauses instead.
```suggestion
and then referencing that entity in a property definition in the same `CREATE` clause is deprecated.
Split the `CREATE` clause into two separate clauses instead.
```

2023-06-22 11:26 UTC, JPryce-Aklundh approved these changes

2023-06-22 11:42 UTC, merged