Use "aggregating functions" consistently
neo4j/docs-cypher pull request #686
Opened 2023-08-09 09:14 UTC by JPryce-Aklundh

Plus some minor editorial corrections.

2023-08-09 09:15 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-cypher-686.surge.sh
<!-- Sticky Pull Request Comment -->

2023-08-10 12:14 UTC, Lojjs requested changes
Thanks for doing this. Just some small side comments

2023-08-10 12:14 UTC, Lojjs commented on modules/ROOT/pages/functions/aggregating.adoc
> +To sort the result set using aggregating functions, the aggregation must be included in the `RETURN` clause used in the `ORDER BY` clause.
To me, this sounds like RETURN is part of ORDER BY rather than the other way around. Maybe it can be further re-formulated?

2023-08-10 12:14 UTC, Lojjs commented on modules/ROOT/pages/functions/aggregating.adoc
> +For instance, `0.1 * (SUM(x.a) / COUNT(x.b))` is an aggregating expression that contains two aggregating functions, `SUM( )` with `x.a` as its argument and `COUNT( )` with `x.b` as its argument.
Not really related, but don't we usually write functions like `sum` and `count` with lowercase?

2023-08-10 12:14 UTC, Lojjs commented on modules/ROOT/pages/functions/aggregating.adoc
> +* an aggregating function, e.g. `SUM(x.a)`,
```suggestion
* an aggregating function, e.g. `sum(x.a)`,
```

2023-08-10 12:14 UTC, Lojjs commented on modules/ROOT/pages/functions/aggregating.adoc
> +For better query readability, Cypher only recognizes a sub-expression in aggregating expressions as a grouping key if the grouping key is either:
I think line 1206 also needs this update in two places

2023-08-11 06:26 UTC, Lojjs approved these changes

2023-08-11 06:45 UTC, merged