Updates the return values to reflect what the product actually returns.
neo4j/docs-cypher pull request #754
Opened 2023-09-29 13:56 UTC by gem-neo4j

2023-09-29 13:57 UTC, gem-neo4j commented
![](https://github.trello.services/images/mini-trello-icon.png) [Log function wrong result](https://trello.com/c/KoW6aBNE/636-log-function-wrong-result)

2023-09-29 13:57 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-cypher-754.surge.sh
<!-- Sticky Pull Request Comment -->

2023-10-02 09:42 UTC, Lojjs requested changes
Two typos and two small suggestions

2023-10-02 09:42 UTC, Lojjs commented on modules/ROOT/pages/functions/mathematical-logarithmic.adoc
> +| `exp()` returns `Infinity` when the return value is greater than the largest `FLOAT` value.
If the docs reviewer agrees, maybe we should add a note here to what the largest FLOAT values is (Java double.MAX_VALUE I believe)

2023-10-02 09:42 UTC, Lojjs commented on modules/ROOT/pages/functions/mathematical-logarithmic.adoc
> +| If (`expression` < 1), then (`log(expression)`) returns `NaN`.
```suggestion
| If (`expression` < 0), then (`log(expression)`) returns `NaN`.
```

2023-10-02 09:42 UTC, Lojjs commented on modules/ROOT/pages/functions/mathematical-logarithmic.adoc
> +| If (`expression` < 1), then (`log10(expression)`) returns `NaN`.
```suggestion
| If (`expression` < 0), then (`log10(expression)`) returns `NaN`.
```

2023-10-02 09:42 UTC, Lojjs commented on modules/ROOT/pages/functions/mathematical-logarithmic.adoc
> +| If (`expression` < 1), then (`log10(expression)`) returns `NaN`.
We might want to rewrite sqrt in the same way to align, right now it says

sqrt(<any negative number>) returns NaN

2023-10-02 11:45 UTC, Lojjs approved these changes

2023-10-02 13:43 UTC, JPryce-Aklundh approved these changes
lgtm 👍

2023-10-02 13:50 UTC, merged